### ISSUE TITLE
NFC won't read MiFare cards on AOSP rom

### ISSUE THREAD

**Issue by VictorRyabov** [sonyxperiadev/device-sony-lilac#29]
Hello, thanks for all the work for AOSP community!
I would like to report that after switching to AOSP on my XZ1 Compact(lilac) I have issues reading MiFare card. I will attach a logcat from stock rom where the card was read successfully and AOSP rom where it failed. This issue was confirmed by other AOSP users. Please. help to resolve this problem. Thank you very much!
[nfc_fail_AOSP.txt](https://github.com/sonyxperiadev/device-sony-lilac/files/1914522/nfc_fail_AOSP.txt)
[nfc stock 8.0.0_SUCCESS.txt](https://github.com/sonyxperiadev/device-sony-lilac/files/1914523/nfc.stock.8.0.0_SUCCESS.txt)

**Comment by jerpelea** [comment]
Hi Victor,
what Mifare card is that ? Is it a German ID?

Regards
Alin

**Comment by VictorRyabov** [comment]
Thank you for your reply!
MIFARE Classic cards are used in CIS countries as a pass for public transport. Can't really tell if they are used in Europe. I'll try to find info on this matter.

Regards
Victor

**Comment by jerpelea** [comment]
Hi 
this is our bug tracker 
https://github.com/sonyxperiadev/bug_tracker/issues?q=is%3Aissue+is%3Aclosed

and there is already a fix for the issue 
https://github.com/sonyxperiadev/bug_tracker/issues/53

Regards
Alin

**Comment by VictorRyabov** [comment]
I am sorry, so you say that the fix is already merged. This means that everything should work fine. But it does not and is confirmed by many users. It is a device tree issue than or what?
Thanks

**Comment by jerpelea** [comment]
did you port the patches to your build?

**Comment by VictorRyabov** [comment]
Yes, the patches are applied to the build.

**Comment by jerpelea** [comment]
did you backport those patches ?
https://android-review.googlesource.com/#/q/topic:%22max_transceive_length%22+(status:open%20OR%20status:merged)

**Comment by VictorRyabov** [comment]
I have now switched to lineage os to see if the issue is there, It is still there, and those patches are part of lineage os.

**Comment by jerpelea** [comment]
in this case is hard to debug since we do not have your Mifare card

**Comment by VictorRyabov** [comment]
I have a spare one and I am willing to send it via international mail. Just pm me where to send it. Thank you very much!

**Comment by jerpelea** [comment]
please open a bug in the bug tracker and see who from community can help you deubg
