### ISSUE TITLE
Flashing AOSP 8.1 on Xperia XZ2

### ISSUE THREAD

**Issue by Calin-Mihnea** [sonyxperiadev/device-sony-lilac#30]
Hello!

I have build AOSP 8.1 for G8441 (which seems to be the XZ1 Compact device) and I am trying to flash the image on an XZ2 device. After following the guide from https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-8-1-oreo-4-4/#tutorial-step-6, I have encountered the error below while flashing *system.img*: 
``
calin@calin-pc:~/aosp_images$ sudo fastboot flash system system.img
``
``
target reported max download size of 536870912 bytes
``
``
erasing 'system'...
``
``
OKAY [ 14.272s]
``
``
sending sparse 'system' (524284 KB)...
``
``
OKAY [ 14.420s]
``
``
writing 'system'...
``
``
OKAY [  0.001s]
``
``
sending sparse 'system' (399512 KB)...
``
``
FAILED (remote: Error: Last flash failed : Volume Full)
``
``
finished. total time: 28.693s
``

Are there any other steps I need to perform in order to get this operation to work? Should I try to build a different AOSP image? Is there a development branch for 8.1 that handles the XZ2 device?

Thank you!

**Comment by jerpelea** [comment]
Xperia XZ2 is not supported yet and will be added soon to the suported devices
Please do not cross flash !

Regards
Alin

**Comment by Calin-Mihnea** [comment]
Is there currently an older version of AOSP or an official Android factory image I can use in order to restore the OS on this device?

**Comment by jerpelea** [comment]
you can always use flashtool to revert the device to the factory software

https://developer.sony.com/develop/open-devices/get-started/flash-tool/

Regards
Alin

**Comment by Calin-Mihnea** [comment]
I tried but the current flash-tool does not support XZ2, as it cannot find a available service for the device.

Receiving the following service log:
``Please refer to update session a52e3f1a-c6aa-4002-bc0a-08ed98d52dc4 if you need to contact Emma support.``

**Comment by jerpelea** [comment]
what model is your XZ2?

**Comment by Calin-Mihnea** [comment]
Model: H8266

**Comment by jerpelea** [comment]
try now !

**Comment by Calin-Mihnea** [comment]
It works now. Thank you for the quick replies.

Best regards,
   Calin

**Comment by lperruchoud** [comment]
Hello, any update on the xz2 support?

**Comment by MartinX3** [comment]
https://github.com/sonyxperiadev/bug_tracker/issues/149
Please follow this issue.

**Comment by MartinX3** [comment]
@Calin-Mihnea

If you want to test my AOSP 8.1 build on your device.
https://forum.xda-developers.com/xperia-xz2/development/recovery-twrp-3-2-2-0-touch-recovery-t3821597

I don't know if it boots.

Btw. don't test my twrp builds.
We still need the bootloader patch from Sony.

**Comment by jerpelea** [comment]
you need bootloader 60 to boot custom ROMs

you can check bootloader version in fastboot

sastbot getvar all

**Comment by MartinX3** [comment]
How does we get version 60?

And is there any ETA?

Takes it months?

**Comment by jerpelea** [comment]
I should be out soon with the next SW update

**Comment by ItzLevvie** [comment]
@MartinX3 Use [Emma](https://developer.sony.com/develop/open-devices/get-started/flash-tool/download-flash-tool)

**Comment by MartinX3** [comment]
Thank you, that's a very helpful information!
