### ISSUE TITLE
Lilac not working in WIFI EAP

### ISSUE THREAD

**Issue by laurenzfg** [sonyxperiadev/device-sony-lilac#41]
Dear Sony development team,

since my phone was updated to Android 9 Oreo, me and other Sony android device users can not use our WIFI EAP secured network at university. The first connects work, but after walking in and out the APs ranges (its a big installation with 500+ APs), the WiFi driver freezes and thus Android is unable to show the WiFi-Network chooser. When opening the WiFi settings app, Android Studio logs that the WiFi component is unable. It'd be glad to provide you with logs.

I tried to get in touch with your customer relations team beforehand by email, but their only suggestion is to reinstall the OS (which I did to be sure). My post on your forum is not getting attention [1]. Nevertheless, the error still persists.

Can you provide me with instructions or an OS patch?

Best regards

Laurenz

[1]: https://talk.sonymobile.com/t5/Xperia-XZ-Premium/Wifi-configuration-failure-after-Android-9-update/m-p/1351740/highlight/false#M15528

**Comment by jerpelea** [comment]
Are you using Official Software or the open source one?
Regards
Alin

**Comment by laurenzfg** [comment]
Hi Alin,

I am using the Official Software. I decided to open a GitHub issue, since nobody replied to my E-Mails.

Best regards

Laurenz

**Comment by laurenzfg** [comment]
This is a WiFi log on error level when the error happens
[wifi_error.log](https://github.com/sonyxperiadev/device-sony-lilac/files/3401968/wifi_error.log)

**Comment by jerpelea** [comment]
I am sorry but that is a different project
Regards
Alin

Get Outlook for Android<https://aka.ms/ghei36>




On Wed, Jul 17, 2019 at 2:59 PM +0200, "Laurenz" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Alin,

I am using the Official Software. I decided to open a GitHub issue, since nobody replied to my E-Mails.

Best regards

Laurenz

**Comment by laurenzfg** [comment]
I understand that this is the Open Source Repository of the Sony AOSP build for my device. But I am sure, that the error results from a bug in the wifi driver. Therefore the error should be kernel-related.
The same error exists on other Sony Android products, but not on other manufacturers devices. This suggests a bug in the shared Android code, probably Sony's Linux fork.

**Comment by jerpelea** [comment]
please test the functionality on Open Devices and report it in the bug tracker git

**Comment by laurenzfg** [comment]
To whom can I send a log of a wifi component which is clearly **not** complying to the current WPA standard?
As much as I like that nowadays IT companies go open about their sources on e.g. GitHub, I still wish to be able to have customer support without going thru installing the current upstream.
