### ISSUE TITLE
Unlocking erases camera DRM

### ISSUE THREAD

**Issue by bobobo1618** [sonyxperiadev/device-sony-lilac#5]
Apologies if this isn't the right place but it's the only place I can think of to bring it up.

AOSP is fantastic but it's severely limited in terms of imaging. The camera DRM is erased when the device is unlocked, crippling image quality. Further exacerbating this is the lack of RAW support in the Camera2 API, preventing app developers from using their own image processing techniques.

**Comment by jerpelea** [comment]
The AOSP software does not use the DRM keys for camera functionality and the keys are not needed for any AOSP component.

I just flashed and tested this device with AOSP and none of the reported issues can be replicated

This maked me wonder if you have the Sony software on your device

**Comment by bobobo1618** [comment]
I'm currently using Sony's retail Android release in order to preserve my DRM keys until a time comes when the community finds a way to back them up prior to decide unlocking.

And yes, AOSP doesn't use the DRM keys. That's the problem. Due to not using the DRM keys, Sony's proprietary but necessary image processing algorithms like noise reduction can't be used and image quality suffers, particularly in low light environments. If you compare photos taken with the same app (say Open Camera) before and after unlocking the device's bootloader, you will see this.

**Comment by kholk** [comment]
Same reply of issue #6 applies.

**Comment by bobobo1618** [comment]
I'm satisfied with that response, thanks for explaining things.
