### ISSUE TITLE
Extremely choppy performance

### ISSUE THREAD

**Issue by bobobo1618** [sonyxperiadev/device-sony-lilac#9]
I'm assuming this is due to the CPU frequency governor but not too sure yet. I was intending to run systrace but ftrace is disabled on my kernel for some reason so I'm unable to debug. I'm running a `-user` build so I'll try with a `userdebug` build in case it's only disabled for `-user`.

**Comment by bobobo1618** [comment]
Ended up adding the relevant kernel config options but `systrace` output fails to open with this message: `The end timestamp of a thread running on CPU 5 is before its start timestamp.`

I checked whether the governor was a problem by simply turning on the `performance` governor and comparing performance and I can confirm that it does lead to _some_ improvement so the current settings aren't perfect but the system is still far from smooth so the bigger problem is elsewhere.

**Comment by jerpelea** [comment]
I use the same device as my DD and I can't see any choppy performance

**Comment by bobobo1618** [comment]
I wonder what the problem is then. I don't have any particularly odd apps installed and the problem is certainly noticable:

- Time from pressing power button to screen coming on from sleep is consistently 1.5-2s (measured)
- Frames are noticably dropped on basic animations like opening the home screen, opening recent apps or opening a new app
- Playing music with the screen off occasionally drops samples
- Playing video occasionally drops frames

I swear I'm not making this up. The time to wake for one is consistently reproducible.

Given that `systrace` isn't working and I can't think of any other way of demonstrating what I'm seeing here's an `atrace` log of just turning the screen on and off a couple of times.

[trace.txt.gz](https://github.com/sonyxperiadev/device-sony-lilac/files/1392082/trace.txt.gz)

**Comment by bobobo1618** [comment]
I `repo sync`ed and installed and the issue seems to have resolved itself, I assume it was a temporary regression that's since been fixed.
